spring.application.name=agrogestao-core
server.address=${JAVA_HOST:127.0.0.1}
server.port=${JAVA_PORT:8081}
spring.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/agrogestao?serverSelectionTimeoutMS=2000}
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
